### ISSUE TITLE
2dEventDisplay.py Terminated

### ISSUE THREAD

**Issue by yang-zhibin** [SND-LHC/sndsw#169]
I am trying to visualize snd event with 2dEventDisplay.py, but got terminated. I tried to run it with default arguments, but got an error in opening the input file. It seems the path in the default argument doesn't match the existing directory. Then I tried to use the files below to run it. 

input file `/eos/experiment/sndlhc/convertedData/physics/2022/run_005000/sndsw_raw-0000.root`
geo file `/eos/experiment/sndlhc/convertedData/physics/2022/run_005000/sndsw_raw-0000.root`

I copy these two files to my working directory (on lxplus) and run `python $SNDSW_ROOT/shipLHC/scripts/2dEventDisplay.py -p ./ -f sndsw_raw-0000.root -g geofile_sndlhc_TI18_V0_2022.root`
Then I got the following information:
```
using geofile: geofile_sndlhc_TI18_V0_2022.root
Info in <TGeoManager::CloseGeometry>: Geometry loaded from file...
Info in <TGeoManager::SetTopVolume>: Top volume is cave. Master volume is cave
Info in <TGeoNavigator::BuildCache>: --- Maximum geometry depth set to 100
Info in <TGeoManager::Voxelize>: Voxelizing...
Info in <TGeoManager::CountLevels>: max level = 7, max placements = 2829
Info in <TGeoManager::CloseGeometry>: 342536 nodes/ 81 volume UID's in FAIR geometry
Info in <TGeoManager::CloseGeometry>: ----------------modeler ready----------------

*************************************************************
     initialisation for run id 0
*************************************************************
-I- FairRunTimeDB::InitContainer() FairBaseParSet
-I- FairRunTimeDB::InitContainer() FairGeoParSet

*************************************************************
     initialisation for run id 0
*************************************************************
-I- FairRunTimeDB::InitContainer() FairBaseParSet
-I- FairRunTimeDB::InitContainer() FairGeoParSet
TTree::Bronch:0: RuntimeWarning: FairEventHeader cannot be split, resetting splitlevel to 0
continue without knowing filling scheme
Terminated 
```
Is it because I used the wrong data as input? Could you please tell me how I could fix this?

**Comment by yang-zhibin** [comment]
There is a mistake in the problem description above, the location of the geo file should be: `/eos/experiment/sndlhc/convertedData/physics/2022/geofile_sndlhc_TI18_V0_2022.root`

**Comment by ThomasRuf** [comment]
try:

python -i $SNDSW_ROOT/shipLHC/scripts/2dEventDisplay.py -p $EOSSHIP/eos/experiment/sndlhc/convertedData/physics/2022/ -f run_005000/sndsw_raw-0000.root

Von: yang-zhibin ***@***.***>
Gesendet: Tuesday, 10 October 2023 17:02
An: SND-LHC/sndsw ***@***.***>
Cc: Subscribed ***@***.***>
Betreff: [SND-LHC/sndsw] 2dEventDisplay.py Terminated (Issue #169)


I am trying to visualize snd event with 2dEventDisplay.py, but got terminated. I tried to run it with default arguments, but got an error in opening the input file. It seems the path in the default argument doesn't match the existing directory. Then I tried to use the files below to run it.

input file /eos/experiment/sndlhc/convertedData/physics/2022/run_005000/sndsw_raw-0000.root
geo file /eos/experiment/sndlhc/convertedData/physics/2022/run_005000/sndsw_raw-0000.root

I copy these two files to my working directory (on lxplus) and run python $SNDSW_ROOT/shipLHC/scripts/2dEventDisplay.py -p ./ -f sndsw_raw-0000.root -g geofile_sndlhc_TI18_V0_2022.root
Then I got the following information:

using geofile: geofile_sndlhc_TI18_V0_2022.root

Info in <TGeoManager::CloseGeometry>: Geometry loaded from file...

Info in <TGeoManager::SetTopVolume>: Top volume is cave. Master volume is cave

Info in <TGeoNavigator::BuildCache>: --- Maximum geometry depth set to 100

Info in <TGeoManager::Voxelize>: Voxelizing...

Info in <TGeoManager::CountLevels>: max level = 7, max placements = 2829

Info in <TGeoManager::CloseGeometry>: 342536 nodes/ 81 volume UID's in FAIR geometry

Info in <TGeoManager::CloseGeometry>: ----------------modeler ready----------------



*************************************************************

     initialisation for run id 0

*************************************************************

-I- FairRunTimeDB::InitContainer() FairBaseParSet

-I- FairRunTimeDB::InitContainer() FairGeoParSet



*************************************************************

     initialisation for run id 0

*************************************************************

-I- FairRunTimeDB::InitContainer() FairBaseParSet

-I- FairRunTimeDB::InitContainer() FairGeoParSet

TTree::Bronch:0: RuntimeWarning: FairEventHeader cannot be split, resetting splitlevel to 0

continue without knowing filling scheme

Terminated

Is it because I used the wrong data as input? Could you please tell me how I could fix this?

**Comment by yang-zhibin** [comment]
> try: python -i $SNDSW_ROOT/shipLHC/scripts/2dEventDisplay.py -p $EOSSHIP/eos/experiment/sndlhc/convertedData/physics/2022/ -f run_005000/sndsw_raw-0000.root 

Thank you for the quick response!
It doesn't terminate this time, but nothing displays. It seems it got into the Python interactive session:
```
initialisation for run id 0
*************************************************************
-I- FairRunTimeDB::InitContainer() FairBaseParSet
-I- FairRunTimeDB::InitContainer() FairGeoParSet
TTree::Bronch:0: RuntimeWarning: FairEventHeader cannot be split, resetting splitlevel to 0
continue without knowing filling scheme
>>>
```
How should I proceed? I tried `drawDetector()` and `loopEvent()`, but nothing was displayed either. 
I also checked my GUI, I connected the lxplus with XQuart from MacOS. I tried `new TCanvas` with root and it worked just fine.

**Comment by ThomasRuf** [comment]
loopEvents(start=0)

if you want to start with first event.
There are many more options available, display of fitted tracks, filter of events, …

Von: yang-zhibin ***@***.***>
Gesendet: Dienstag, 10. Oktober 2023 18:08
An: SND-LHC/sndsw ***@***.***>
Cc: Thomas Ruf ***@***.***>; Comment ***@***.***>
Betreff: Re: [SND-LHC/sndsw] 2dEventDisplay.py Terminated (Issue #169)


try: python -i $SNDSW_ROOT/shipLHC/scripts/2dEventDisplay.py -p $EOSSHIP/eos/experiment/sndlhc/convertedData/physics/2022/ -f run_005000/sndsw_raw-0000.root

Thank you for the quick response!
It doesn't terminate this time, but nothing displays. It seems it got into the Python interactive session:

initialisation for run id 0

*************************************************************

-I- FairRunTimeDB::InitContainer() FairBaseParSet

-I- FairRunTimeDB::InitContainer() FairGeoParSet

TTree::Bronch:0: RuntimeWarning: FairEventHeader cannot be split, resetting splitlevel to 0

continue without knowing filling scheme

>>>

How should I proceed? I tried drawDetector() and loopEvent(), but nothing was displayed either.
I also checked my GUI, I connected the lxplus with XQuart from MacOS. I tried new TCanvas with root and it worked just fine.
