### ISSUE TITLE
ROOT hadd error messages

### ISSUE THREAD

**Issue by antonioiuliano2** [SND-LHC/sndsw#36]
Dear all,

I usually divide neutrino simulations in various HTCondor runs, then I merge the produced files with hadd. However, for the new snd simulations (basically after the FairROOT update) I get a lot of error messages like this one:

Error in <TStreamerInfo::WriteBuffer>: The element ShipMCTrack::fPx type 208 (double) is not supported yet

Output file is produced and it seems, at least at first glance, fine (Branches listed in the error present entries). But I have never seen this message before.

This issue may not depend from sndsw but from FairShip. However, as I do not have a recent HTCondor session from FairShip to test with, I open a first issue thread here.

Best regards,
Antonio

**Comment by ThomasRuf** [comment]
Hi Antonio,
I know this error. See solution below. You are probably merging productions with different versions of the class.

Cheers,
Thomas


Von: Philippe G Canal <pcanal@fnal.gov>
Gesendet: Donnerstag, 4. Juni 2020 19:42
An: Thomas Ruf <Thomas.Ruf@cern.ch>
Betreff: Re: AW: AW: root problem

you are welcome ;)
On 6/4/20 12:32 PM, Thomas Ruf wrote:
Changing version number did the job. Thanks for the hint.

Best regards,
Thomas

Von: Thomas Ruf
Gesendet: Donnerstag, 4. Juni 2020 18:01
An: Philippe G Canal <pcanal@fnal.gov><mailto:pcanal@fnal.gov>; Pere Mato Vila <Pere.Mato@cern.ch><mailto:Pere.Mato@cern.ch>
Cc: Philippe Canal <philippe.canal@cern.ch><mailto:philippe.canal@cern.ch>
Betreff: AW: AW: root problem

BINGO! This is the difference between the use cases. The one which causes the problem is reading particles from a ROOT file, made with a much older version of ROOT.  I will try with increasing the version number.

Cheers,
Thomas

Von: Philippe G Canal <pcanal@fnal.gov<mailto:pcanal@fnal.gov>>
Gesendet: Donnerstag, 4. Juni 2020 17:52
An: Thomas Ruf <Thomas.Ruf@cern.ch<mailto:Thomas.Ruf@cern.ch>>; Pere Mato Vila <Pere.Mato@cern.ch<mailto:Pere.Mato@cern.ch>>
Cc: Philippe Canal <philippe.canal@cern.ch<mailto:philippe.canal@cern.ch>>
Betreff: Re: AW: root problem

Hi Thomas,

This problem would appear only if an "old" file is being read.  It is very plausible that "old" is relative.  So it might depends on which files are read.

Cheers,
Philippe.
On 6/4/20 10:42 AM, Thomas Ruf wrote:
Hi,
Thanks for the fast response. Very useful hints. I will try what Philippe suggests. I am only wondering why it happens for one use case and not the others. All use cases are very similar, run a MC generator, transport particles through Geant4 (behind TVirtualMC) and write out events. So, in all cases FairMCEventHeader and FairMCPoint are made persistent.

Cheers,
Thomas

Von: Philippe G Canal <pcanal@fnal.gov><mailto:pcanal@fnal.gov>
Gesendet: Donnerstag, 4. Juni 2020 17:35
An: Pere Mato Vila <Pere.Mato@cern.ch><mailto:Pere.Mato@cern.ch>; Thomas Ruf <Thomas.Ruf@cern.ch><mailto:Thomas.Ruf@cern.ch>
Cc: Philippe Canal <philippe.canal@cern.ch><mailto:philippe.canal@cern.ch>
Betreff: Re: root problem

Hi Thomas,

This seems to indicates that

a) FairMCEventHeader::fY and FairMCPoint::fLength are or were of type Double32_t

b) The old (or the new) version was/is not properly recognizing that fact.

c) The new version is doing a better job and is marking the member as needing a conversion

d) The version number for FairMCEventHeader and FairMCPoint were not increased

e) Consequently it tries to write the member marked as need conversion ... which is not supported yet.

So my guess is that to solve the problem you "just" to increase the version number of FairMCEventHeader and FairMCPoint.
You may also want to check whether the member are meant (or not) to be stored as Double32_t.

Cheers,
Philippe.
On 6/4/20 10:27 AM, Pere Mato Vila wrote:
Hi Thomas,

  I have no idea, but perhaps Philippe (in CC:) can give you a hint of what the problem is.  Could it be some data corruption?
  Cheers,

Pere




On 4 Jun 2020, at 17:14, Thomas Ruf <Thomas.Ruf@cern.ch<mailto:Thomas.Ruf@cern.ch>> wrote:

Hi Pere,
How are you? Hope you and your family are doing well.
After a long time, I am contacting you again for a ROOT issue. I recently moved to the latest version of ROOT (no other change!)  and encounter a strange problem. In one of the FairShip applications which I have, I get the following type of errors:

Error in <TStreamerInfo::WriteBuffer>: The element FairMCEventHeader::fY type 209 (double) is not supported yet
Error in <TStreamerInfo::WriteBuffer>: The element FairMCPoint::fLength type 209 (double) is not supported yet
…
It obviously has to do with persistency. However, don’t understand why it appears for one application and not the others. I was trying to debug from where it originates using gdb, but I failed. The last thing I could figure out, it is caused after calling G4RunManager::Initialize(), which is also strange.
I was wondering if one could attack this problem from the ROOT side. Under what conditions would such a message be displayed?

Cheers,
Thomas






Von: Antonio <notifications@github.com>
Gesendet: Donnerstag, 7. Januar 2021 18:20
An: SND-LHC/sndsw <sndsw@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [SND-LHC/sndsw] ROOT hadd error messages (#36)


Dear all,

I usually divide neutrino simulations in various HTCondor runs, then I merge the produced files with hadd. However, for the new snd simulations (basically after the FairROOT update) I get a lot of error messages like this one:

Error in TStreamerInfo::WriteBuffer: The element ShipMCTrack::fPx type 208 (double) is not supported yet

Output file is produced and it seems, at least at first glance, fine (Branches listed in the error present entries). But I have never seen this message before.

This issue may not depend from sndsw but from FairShip. However, as I do not have a recent HTCondor session from FairShip to test with, I open a first issue thread here.

Best regards,
Antonio

**Comment by antonioiuliano2** [comment]
Thank you Thomas for your clear explanation.

I will check the class versions, then test hadd with new simulations.

Best regards,
Antonio

**Comment by ThomasRuf** [comment]
Hi Antonio,
it might be enough to change the version number in the header, recompile. No new simulation needed.
Cheers,
Thomas

Von: Antonio <notifications@github.com>
Gesendet: Friday, 8 January 2021 11:10
An: SND-LHC/sndsw <sndsw@noreply.github.com>
Cc: Thomas Ruf <Thomas.Ruf@cern.ch>; Comment <comment@noreply.github.com>
Betreff: Re: [SND-LHC/sndsw] ROOT hadd error messages (#36)


Thank you Thomas for your clear explanation.

I will check the class versions, then test hadd with new simulations.

Best regards,
Antonio

**Comment by olantwin** [comment]
@antonioiuliano2 Could you increment the version of the affected classes?

**Comment by antonioiuliano2** [comment]
Dear Oliver,

I have updated the SHiP MCTrack one, but it also complains about FairROOT classes:
.......
Error in <TStreamerInfo::WriteBuffer>: The element FairMCPoint::fPx type 208 (double) is not supported yet

Error in <TStreamerInfo::WriteBuffer>: The element FairMCPoint::fPy type 208 (double) is not supported yet
.....and many other messages for all FairMCPoint attributes

Error in <TStreamerInfo::WriteBuffer>: The element FairMCEventHeader::fX type 208 (double) is not supported yet
.....and so on

I can try changing our derivate class versions (ScifiPoint, MuFilterPoint), and see if the errors remain.

**Comment by olantwin** [comment]
Maybe this is a bug that needs to be brought to the attention of the FairRoot team?

**Comment by antonioiuliano2** [comment]
It is a possibility, since this error appears in simulations done after the FairROOT update.
I confirm that updating the derivate class versions does not solve this issue.

**Comment by ThomasRuf** [comment]
In my case, I cloned FairRoot and changed the class version in there.

**Comment by olantwin** [comment]
If that fixes the issue, it's definitely something we should take to the FairRoot team.

**Comment by antonioiuliano2** [comment]
We can close this issue, since it was solved along with #74.

Thanks again to @ThomasRuf for the solution
